import { sheriff } from 'eslint-config-sheriff';
import nextPlugin from '@next/eslint-plugin-next';

const sheriffOptions = {
  react: true,
  lodash: false,
  remeda: false,
  next: false,
  astro: false,
  playwright: false,
  storybook: true,
  jest: false,
  vitest: false,
};

const eslintConfig = [
  ...sheriff(sheriffOptions),
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    linterOptions: {
      reportUnusedDisableDirectives: false,
    },
    languageOptions: {
      parserOptions: {
        project: false,
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          checksVoidReturn: false,
        },
      ],
      'no-console': 'off',
      'no-restricted-imports': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-import-type-side-effects': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-template-expression': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/array-type': 'off',
      'react-refresh/only-export-components': 'off',
      'react/function-component-definition': 'off',
      'react/jsx-no-useless-fragment': 'off',
      'react/jsx-sort-props': 'off',
      'react/no-array-index-key': 'off',
      'react-hooks/exhaustive-deps': 'warn',
      'simple-import-sort/imports': 'off',
      '@stylistic/padding-line-between-statements': 'off',
      'arrow-return-style/arrow-return-style': 'off',
      'curly': 'off',
      'eqeqeq': 'off',
      '@typescript-eslint/naming-convention': 'off',
      'import/newline-after-import': 'off',
      'jsdoc/require-description-complete-sentence': 'off',
      'jsdoc/convert-to-jsdoc-comments': 'off',
      'func-style': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-implicit-coercion': 'off',
      'operator-assignment': 'off',
      'prefer-destructuring': 'off',
      'no-param-reassign': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/catch-error-name': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/switch-case-braces': 'off',
      'react/no-multi-comp': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/require-await': 'off',
      'tsdoc/syntax': 'off',
      'fsecond/valid-event-listener': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      'fsecond/prefer-destructured-optionals': 'off',
      '@typescript-eslint/no-misused-spread': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@regru/prefer-early-return/prefer-early-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      'sonarjs/no-duplicate-string': 'off',
      'regexp/no-obscure-range': 'off',
      'unicorn/prefer-type-error': 'off',
      'no-restricted-syntax/noClasses': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      'no-fallthrough': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@next/next/no-img-element': 'warn',
    },
  },
];
export default eslintConfig;
